export enum AppErrorTypes {
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    CONSTRAINT_ERROR = "CONSTRAINT_ERROR",
}

export enum InfraErrorTypes {
    DATABASE_ERROR = "DATABASE_ERROR",
}
