export enum AppErrorTypes {
    ORDER_PRINTING_NOT_FOUND = "ORDER_PRINTING_NOT_FOUND",
    MESA_NOT_FOUND = "MESA_NOT_FOUND",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    DATABASE_ERROR = "DATABASE_ERROR",
    CONSTRAINT_ERROR = "CONSTRAINT_ERROR",
    MESA_ALREADY_BLOCKED = "MESA_ALREADY_BLOCKED",
}
